notifications:
    slack: 
        rooms: 
            - j-b-t:OIVY6djyR2ND1vGpgDR2G29R#general
        on_success: change
        on_failure: always
    email:
        on_success: never
        on_failure: change  